name = "cancion-worker"
main = "src/index.js"
compatibility_date = "2024-07-25"

# Configuración para el servidor de desarrollo local ('wrangler dev')
[dev]
# Escucha en la IP 0.0.0.0 para ser accesible desde fuera del contenedor (desde tu localhost).
ip = "0.0.0.0"
# El puerto en el que correrá el servidor de desarrollo.
port = 8787

[[d1_databases]]
database_name = "birthday-songs"
database_id = "b678583e-4624-4767-99dd-a8ebc149f26c"
binding = "SONGS_DB"
migrations_dir = "migrations"

[[r2_buckets]]
bucket_name = "birthday-songs"
binding = "SONGS_STORAGE"

[observability.logs]
enabled = true

[assets]
directory = "./static"
binding = "ASSETS"

[ai]
binding = "AI"
